### ISSUE TITLE
Conversion to swift 3

### ISSUE THREAD

**Issue by JFSene** [moraisandre/SwiftMaskText#1]
Cara alguma chance de converter o projeto para swift 3?

**Comment by andre991** [comment]
Eu traduzi essa framework para Swift 3, criei o pull request para que seja atualizado. Caso preferir pode usar o meu fork enquanto o repositório não é atualizado: https://github.com/andre991/SwiftMaskText

Abraços.

**Comment by moraisandre** [comment]
Convertido para Swift 3 graças ao @andre991 

Converted to Swift 3 thanks to @andre991
