### ISSUE TITLE
Ambiguous use of 'uppercased()'

### ISSUE THREAD

**Issue by diegodsp** [moraisandre/SwiftMaskText#14]
Ajustei no meu projeto local nas linhas: 64, 74, 97 e 104

Ex.: text[i].lowercased()
Trocar para: String(text[i]).lowercased()

**Comment by moraisandre** [comment]
Feito e já esta disponível no cocoa pods

**Comment by alanbarboza** [comment]
> Feito e já esta disponível no cocoa pods

Em qual versão está incluso o ajuste?
