### ISSUE TITLE
Muito bom seu plugin

### ISSUE THREAD

**Issue by carlosguedes** [moraisandre/SwiftMaskText#5]
Prezado, parabéns pelo projeto. Excelente e sem dúvidas o MELHOR que existe até hoje. Todos que pesquisei são complicados, mal feitos e cheio de bugs.

Gostaria de te perguntar: Como eu faria para criar uma mascara para e-mail? Considerando que não é possível estimar a quantidade de caracteres antes e após o @?

Obrigado

**Comment by moraisandre** [comment]
Boa noite!

A ideia da máscara é para campos com posições fixas, como RG, CPF. Para um e-mail não faria sentido.

Imagino que você procura uma validação para verificar se a string é um e-mail válido ou não. 
Para isso tente usar o código descrito na resposta do StackOverflow:
https://stackoverflow.com/questions/25471114/how-to-validate-an-e-mail-address-in-swift

**Comment by carlosguedes** [comment]
Muito obrigado pela ajuda!

**Comment by moraisandre** [comment]
Denada!
