### ISSUE TITLE
No momento de instalar o POD em meu projeto tive este problema

### ISSUE THREAD

**Issue by carlosguedes** [moraisandre/SwiftMaskText#6]
[!] Error installing SwiftMaskText
[!] /usr/bin/git clone https://github.com/moraisandre/SwiftMaskText.git /var/folders/_1/fsh6qv1x2dsgv67z5z5nr6fm0000gn/T/d20180322-22413-xvu5hs --template= --single-branch --depth 1 --branch 1.0.3

Cloning into '/var/folders/_1/fsh6qv1x2dsgv67z5z5nr6fm0000gn/T/d20180322-22413-xvu5hs'...
warning: Could not find remote branch 1.0.3 to clone.
fatal: Remote branch 1.0.3 not found in upstream origin

**Comment by moraisandre** [comment]
Olá! Você conseguiu resolver esse problema? O que você fez?

**Comment by carlosguedes** [comment]
Prezado, tudo bem? Consegui sim! Na verdade meu Podfile estava com a build
version comentada. Desta maneira, acredito que quando a build está
comentada ele tenta buscar uma versão anterior. No caso a 1.0.3 quando na
verdade, seu build está na 1.0.5.


Abraços

Atenciosamente,

Carlos Guedes
