### ISSUE TITLE
Inherit permission

### ISSUE THREAD

**Issue by lucaspedrazoli** [moraisandre/SwiftMaskText#9]
we could change the `SwiftMaskField` class to `open` instead of `public` to permit inherit

**Comment by moraisandre** [comment]
Hey Lucas Pedrazoli,

Why do you want to inherit the SwiftMaskField? There is any good reason for it? cuz I can't think of any

**Comment by lucaspedrazoli** [comment]
Because with `inherit` we can create a Visual Component, and these components can have reusable properties and functionalities. Let's suppose all text field that uses mask will have a red border bottom. If the system have a class to inherit I wont need to always add this border.

**Comment by moraisandre** [comment]
Hey thanks for the explanation, I've changed and already pushed it
